### ISSUE TITLE
Clarification Request

### ISSUE THREAD

**Issue by wjsmith** [sciurius/MSPro-Tools#1]
HI -

hope this is an ok way to ask for a clarification on your scripts.  First though, I appreciate your making this available!  I was after a way to change a couple of meta data fields on a large song file library without having to edit individual files or use the batch edit process in the app.  So, my question is, after running the upd_meta script to add data to the .db file via JSON, I'm assuming the msb_relocate script is what is used to repack all of the unpacked files from the msb_unpack script into a single msb to import back into the mobile app. Is that correct? 

Thanks again!

**Comment by sciurius** [comment]
On Sun, 16 Oct 2016 20:26:57 -0700
wjsmith notifications@github.com wrote:

> hope this is an ok way to ask for a clarification on your scripts.  First
> though, I appreciate your making this available!  I was after a way to
> change a couple of meta data fields on a large song file library without
> having to edit individual files or use the batch edit process in the
> app.  So, my question is, after running the upd_meta script to add data
> to the .db file via JSON, I'm assuming the msb_relocate script is what is
> used to repack all of the unpacked files from the msb_unpack script into
> a single msb to import back into the mobile app. Is that correct? 

As you correctly assumed, upd_meta updates a local copy of the
mobilesheets.db. So what you need to do is:
1. Copy the actual database from the tablet to your PC (and make a full
   backup!).
2. Run upd-meta to update this database.
3. Copy the updated mobilesheets.db back to the tablet.

I hope this makes it a bit more clear.

In any case, make full backups first so you can restore if the results are
not to your liking.

Happy hacking,
    Johan

**Comment by wjsmith** [comment]
Johan,

Thank you for your response!  Unfortunately, I'm having trouble getting the `upd_meta` script to work like the `get_meta` script.  I can successfully pull the json info from the db using the latter, but when using the former, I don't seem to be updating the .db file because if I run another `get_meta` on the same file, the changes I am attempting to make are not being made.

For example:

If this is the contents of my `metadata.json` file:

``` json
[
   {
      "artists" : [ "Matchbox 20" ],
      "songid" : 2,
   }
]
```

and I run the following command: `perl script/upd_meta.pl metadata.json --db=mobilesheets.db`, there are no error messages and the timestamp on the db file does not change.  If I run `perl script/get_meta.pl --db=mobilesheets.db >> output.json`, then this is what that songs information still says in output.json:

``` json
[
...
   {
      "artists" : [ "Matchbox Twenty" ],
      "paths" : [
         {
            "fileid" : 1620,
            "pageorder" : "1-1",
            "path" : "/storage/emulated/0/Android/data/com.zubersoft.mobilesheetspro/files/3am/3am.pdf",
            "source" : "sdcard",
            "type" : "PDF"
         }
      ],
      "songid" : 2,
      "sourcetypes" : [ "Sheet Music" ],
      "title" : "3 AM"
   },
...
]
```

The change I'm expecting is for the artist to say "Matchbox 20" instead of "Matchbox Twenty" like it originally said.
- I am using the `--db` flag to specify the db file because when this didn't work the first time, I wasn't sure where the default location the script looked for the db file in was.  Do I need to specify a full path?  If so, are "Windows-style" paths acceptable?
- We also are intending to change the `composers` field, but noticed that the `get_meta` script doesn't output the `composers` field.  If I include that field in the json file to update with, will that field get updated in the db file as well?

Thank you!

**Comment by sciurius** [comment]
> ... I don't seem to be updating the .db file because if I
> run another `get_meta` on the same file, the changes I am attempting to
> make are not being made.

upd_meta did not look for changes in artists and composers. I've updated
the program so this should work now.

You didn't got an error because there was nothing to change.

> - I am using the `--db` flag to specify the db file because when this
>   didn't work the first time, I wasn't sure where the default location the
>   script looked for the db file in was.

By default it is "mobilesheets.db" in the current directory.

> Do I need to specify a full path?

No, any valid path will do, relative paths included.

> If so, are "Windows-style" paths acceptable?

I have no idea, since I do not use Windows. You may have to double or
quadruple the backslashes. Using forward slashes instead of backslashes is
reported to work as well.

You try some variations and you'll find out :) .

> - We also are intending to change the `composers` field, but noticed that
>   the `get_meta` script doesn't output the `composers` field.  If I include
>   that field in the json file to update with, will that field get updated
>   in the db file as well?

The composers info should be included in the get_meta output. I see
entries like:

   {
      "artists" : [ "The Dubliners" ],
      "collections" : [ "HowsaGoin!" ],
      "composers" : [ "Ewan MacColl" ],
      "custom2" : "1",
      "keys" : [ "A" ],
   ...

upd_meta will now also handle composers.

Don't forget to make backups!

-- Johan

**Comment by wjsmith** [comment]
Worked perfectly!!  Thanks a lot for sharing this and for your clarifications!!
